package session_test

import (
	"errors"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/curbol/unity-sync/internal/session"
)

// Payloads are inlined rather than kept as testdata files: the repo's .gitignore matches
// *.curl and cookies.txt at any depth, so file fixtures would be silently uncommitted
// and CI would fail on missing testdata.
const curlPaste = `curl 'https://assetstore.unity.com/api/graphql/batch' \
  -H 'accept: application/json' \
  -H 'Cookie: _csrf=stale; LS=the-credential; DS=abc; activeOrgId=123' \
  --data-raw '[]'`

// A real export marks HttpOnly rows with a #HttpOnly_ prefix on the record itself.
const cookiesTxt = "# Netscape HTTP Cookie File\n" +
	"# This file was generated by a browser extension\n" +
	"#HttpOnly_.unity.com\tTRUE\t/\tTRUE\t0\tLS\tthe-credential\n" +
	"assetstore.unity.com\tFALSE\t/\tTRUE\t0\tDS\tabc\n" +
	"example.com\tFALSE\t/\tFALSE\t0\tunrelated\tnope\n"

func write(t *testing.T, name, body string) string {
	t.Helper()
	p := filepath.Join(t.TempDir(), name)
	if err := os.WriteFile(p, []byte(body), 0o600); err != nil {
		t.Fatal(err)
	}
	return p
}

func TestResolveReadsAPastedCurlCommand(t *testing.T) {
	got, err := session.Resolve(write(t, "session.curl", curlPaste))
	if err != nil {
		t.Fatalf("Resolve: %v", err)
	}
	if !strings.Contains(got, "LS=the-credential") {
		t.Errorf("header %q lost the credential", got)
	}
	if !strings.Contains(got, "DS=abc") {
		t.Errorf("header %q dropped an ordinary cookie", got)
	}
}

// The credential is HttpOnly. A parser that treats every '#' line as a comment drops
// exactly the cookie that authenticates and then reports "no cookies found".
func TestCookiesTxtKeepsHttpOnlyRecords(t *testing.T) {
	got, err := session.Resolve(write(t, "cookies.txt", cookiesTxt))
	if err != nil {
		t.Fatalf("Resolve: %v", err)
	}
	if !strings.Contains(got, "LS=the-credential") {
		t.Errorf("header %q dropped the #HttpOnly_ record", got)
	}
}

// The storefront sets some cookies host-only and others on Domain=.unity.com, and which
// scope LS uses was never established, so both must be accepted.
func TestCookiesTxtAcceptsTheWholeUnityFamilyAndNothingElse(t *testing.T) {
	body := "#HttpOnly_assetstore.unity.com\tFALSE\t/\tTRUE\t0\tLS\thost-only\n" +
		".unity.com\tTRUE\t/\tFALSE\t0\twide\tyes\n" +
		"evil.com\tFALSE\t/\tFALSE\t0\tleaked\tno\n"
	got, err := session.Resolve(write(t, "cookies.txt", body))
	if err != nil {
		t.Fatalf("Resolve: %v", err)
	}
	for _, want := range []string{"LS=host-only", "wide=yes"} {
		if !strings.Contains(got, want) {
			t.Errorf("header %q is missing %q", got, want)
		}
	}
	if strings.Contains(got, "leaked") {
		t.Errorf("header %q carries a cookie from an unrelated site", got)
	}
}

func TestMissingCredentialIsNamedBeforeAnyRequest(t *testing.T) {
	body := "assetstore.unity.com\tFALSE\t/\tTRUE\t0\tDS\tabc\n"
	_, err := session.Resolve(write(t, "cookies.txt", body))
	var missing *session.ErrNoCredential
	if !errors.As(err, &missing) {
		t.Fatalf("Resolve = %v, want ErrNoCredential", err)
	}
	if !strings.Contains(err.Error(), "LS") {
		t.Errorf("diagnostic %q does not name the missing cookie", err)
	}
}

// An export whose header comment mentions curl must still parse as a cookies.txt.
func TestCurlDetectionUsesStructureNotTheWord(t *testing.T) {
	body := "# Generated for use with curl\n" +
		"#HttpOnly_.unity.com\tTRUE\t/\tTRUE\t0\tLS\tthe-credential\n"
	if _, err := session.Resolve(write(t, "cookies.txt", body)); err != nil {
		t.Fatalf("Resolve: %v", err)
	}
}

func TestHeaderIsDeterministic(t *testing.T) {
	p := write(t, "session.curl", curlPaste)
	first, err := session.Resolve(p)
	if err != nil {
		t.Fatal(err)
	}
	for range 5 {
		again, err := session.Resolve(p)
		if err != nil {
			t.Fatal(err)
		}
		if again != first {
			t.Fatalf("header varies between reads:\n%q\n%q", first, again)
		}
	}
}

func TestWithCSRFReplacesRatherThanAppends(t *testing.T) {
	got := session.WithCSRF("LS=cred; _csrf=stale; DS=abc", "fresh")
	if strings.Count(got, "_csrf=") != 1 {
		t.Errorf("header %q has %d _csrf cookies, want exactly 1", got, strings.Count(got, "_csrf="))
	}
	if !strings.Contains(got, "_csrf=fresh") {
		t.Errorf("header %q kept the stale token", got)
	}
	if !strings.Contains(got, "LS=cred") {
		t.Errorf("header %q lost the credential", got)
	}
	added := session.WithCSRF("LS=cred", "fresh")
	if !strings.Contains(added, "_csrf=fresh") {
		t.Errorf("header %q did not gain a token when none was present", added)
	}
}

func TestDiscoverPrefersSessionCurl(t *testing.T) {
	dir := t.TempDir()
	if _, ok := session.Discover(dir); ok {
		t.Fatal("Discover found a session in an empty dir")
	}
	if err := os.WriteFile(filepath.Join(dir, "cookies.txt"), []byte("x"), 0o600); err != nil {
		t.Fatal(err)
	}
	got, ok := session.Discover(dir)
	if !ok || filepath.Base(got) != "cookies.txt" {
		t.Fatalf("Discover = %q, %v; want the cookies.txt", got, ok)
	}
	if err := os.WriteFile(filepath.Join(dir, "session.curl"), []byte("x"), 0o600); err != nil {
		t.Fatal(err)
	}
	got, _ = session.Discover(dir)
	if filepath.Base(got) != "session.curl" {
		t.Errorf("Discover = %q, want session.curl to win", got)
	}
}
