package session_test

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/curbol/unity-sync/internal/session"
)

// Payloads are inlined rather than kept as testdata files: the repo's .gitignore matches
// *.curl and cookies.txt at any depth, so file fixtures would be silently uncommitted
// and CI would fail on missing testdata.
const curlPaste = `curl 'https://assetstore.unity.com/api/graphql/batch' \
  -H 'accept: application/json' \
  -H 'Cookie: _csrf=stale; LS=the-credential; DS=abc; activeOrgId=123' \
  --data-raw '[]'`

// A real export marks HttpOnly rows with a #HttpOnly_ prefix on the record itself.
const cookiesTxt = "# Netscape HTTP Cookie File\n" +
	"# This file was generated by a browser extension\n" +
	"#HttpOnly_.unity.com\tTRUE\t/\tTRUE\t0\tLS\tthe-credential\n" +
	"assetstore.unity.com\tFALSE\t/\tTRUE\t0\tDS\tabc\n" +
	"example.com\tFALSE\t/\tFALSE\t0\tunrelated\tnope\n"

func write(t *testing.T, name, body string) string {
	t.Helper()
	p := filepath.Join(t.TempDir(), name)
	if err := os.WriteFile(p, []byte(body), 0o600); err != nil {
		t.Fatal(err)
	}
	return p
}

func TestResolveReadsAPastedCurlCommand(t *testing.T) {
	got, _, err := session.ResolveFrom(write(t, "session.curl", curlPaste))
	if err != nil {
		t.Fatalf("Resolve: %v", err)
	}
	if !strings.Contains(got, "LS=the-credential") {
		t.Errorf("header %q lost the credential", got)
	}
	if !strings.Contains(got, "DS=abc") {
		t.Errorf("header %q dropped an ordinary cookie", got)
	}
}

// An export whose header comment mentions curl must still parse as a cookies.txt.
func TestCurlDetectionUsesStructureNotTheWord(t *testing.T) {
	body := "# Generated for use with curl\n" +
		"#HttpOnly_.unity.com\tTRUE\t/\tTRUE\t0\tLS\tthe-credential\n"
	if _, _, err := session.ResolveFrom(write(t, "cookies.txt", body)); err != nil {
		t.Fatalf("Resolve: %v", err)
	}
}

func TestHeaderIsDeterministic(t *testing.T) {
	p := write(t, "session.curl", curlPaste)
	first, _, err := session.ResolveFrom(p)
	if err != nil {
		t.Fatal(err)
	}
	for range 5 {
		again, _, err := session.ResolveFrom(p)
		if err != nil {
			t.Fatal(err)
		}
		if again != first {
			t.Fatalf("header varies between reads:\n%q\n%q", first, again)
		}
	}
}

func TestDiscoverPrefersSessionCurl(t *testing.T) {
	dir := t.TempDir()
	if _, ok := session.Discover(dir); ok {
		t.Fatal("Discover found a session in an empty dir")
	}
	if err := os.WriteFile(filepath.Join(dir, "cookies.txt"), []byte("x"), 0o600); err != nil {
		t.Fatal(err)
	}
	got, ok := session.Discover(dir)
	if !ok || filepath.Base(got) != "cookies.txt" {
		t.Fatalf("Discover = %q, %v; want the cookies.txt", got, ok)
	}
	if err := os.WriteFile(filepath.Join(dir, "session.curl"), []byte("x"), 0o600); err != nil {
		t.Fatal(err)
	}
	got, _ = session.Discover(dir)
	if filepath.Base(got) != "session.curl" {
		t.Errorf("Discover = %q, want session.curl to win", got)
	}
}

// Every spelling a real browser's "Copy as cURL" produces has to yield the same header.
// The release ships Windows binaries and the README sends those users to DevTools, where
// the copy is double-quoted — a form no other test in the tree exercises, so tightening
// either regex would break every Windows paste with the suite green.
func TestEveryCurlPasteSpellingYieldsTheSameHeader(t *testing.T) {
	const cookie = "_csrf=stale; LS=the-credential; DS=abc"
	for _, tc := range []struct{ name, body string }{
		{"single-quoted", `curl 'https://assetstore.unity.com/' -H 'Cookie: ` + cookie + `'`},
		// Windows: cmd and PowerShell both copy with double quotes.
		{"double-quoted", `curl "https://assetstore.unity.com/" -H "Cookie: ` + cookie + `"`},
		{"long-flag", `curl 'https://assetstore.unity.com/' --header 'Cookie: ` + cookie + `'`},
		{"long-flag double-quoted", `curl "https://assetstore.unity.com/" --header "Cookie: ` + cookie + `"`},
		// Chrome writes the header name lowercase.
		{"lowercase header name", `curl 'https://assetstore.unity.com/' -H 'cookie: ` + cookie + `'`},
		// curl.exe is what a Windows paste names, so the structural check cannot key on
		// the literal "curl ".
		{"curl.exe", `curl.exe "https://assetstore.unity.com/" -H "Cookie: ` + cookie + `"`},
	} {
		t.Run(tc.name, func(t *testing.T) {
			got, _, err := session.ResolveFrom(write(t, "session.curl", tc.body))
			if err != nil {
				t.Fatalf("Resolve: %v", err)
			}
			if !strings.Contains(got, "LS=the-credential") {
				t.Errorf("header %q lost the credential", got)
			}
			if !strings.Contains(got, "DS=abc") {
				t.Errorf("header %q dropped an ordinary cookie", got)
			}
		})
	}
}

// A paste that is a curl command but carries no Cookie header has to say so. Falling
// through to the cookies.txt parser would report a parse failure about a format the file
// is not in.
func TestACurlPasteWithNoCookieHeaderSaysSo(t *testing.T) {
	body := `curl 'https://assetstore.unity.com/' -H 'accept: application/json'`
	_, _, err := session.ResolveFrom(write(t, "session.curl", body))
	if err == nil {
		t.Fatal("a curl paste with no Cookie header resolved")
	}
	if !strings.Contains(err.Error(), "Cookie") {
		t.Errorf("error %q does not name the missing Cookie header", err)
	}
}
